### ISSUE TITLE
JAMP won't work with up to date cutadapt

### ISSUE THREAD

**Issue by DominikBuchner** [VascoElbrecht/JAMP#22] opened 2021-01-27 07:26 UTC
Hi Vasco,
JAMP does not seem to work with the latest version of cutadapt. 
After downgrading to 2.5 everything works as usual.
Maybe fix this for performance?

**Comment by VascoElbrecht** [comment] 2021-01-27 13:21
Thank you for letting me know. I will fix this the next days =)

**Comment by dleopold** [comment] 2021-01-27 14:11
I believe the problem is that the input file type to cutadapt is always auto detected and the -f flag is no longer accepted. The -f flag has been ignored by cutadapt since v2.0. But, including it for the most recent version causes it to fail.

**Comment by VascoElbrecht** [comment] 2021-05-12 23:15
fixed now, sorry for taking so long with it ^^ lots of other things going on

**Closed as completed by VascoElbrecht** 2021-05-12 23:15 UTC
Labels: bug
